#!/usr/bin/env bash
set -e

PORT=${PORT:-8099}
HOST=${HOST:-::}
BASE_PATH=${BASE_PATH:-}
WORKSPACE_ROOT=${WORKSPACE_ROOT:-/home/hermes-admin/projects}
ALLOWED_ROOT=${ALLOWED_ROOT:-/home/hermes-admin}
AUTH_MODE=${AUTH_MODE:-none}
AUTH_PASSWORD=${AUTH_PASSWORD:-}
APP_URL=${APP_URL:-http://localhost:${PORT}}
SESSION_SECRET=${SESSION_SECRET:-}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
GOOGLE_ALLOWED_EMAILS=${GOOGLE_ALLOWED_EMAILS:-}

cd /home/hermes-admin/projects/hugcode/server
echo "Starting HugCode on host port $PORT (BASE_PATH='${BASE_PATH}')..."
PORT=$PORT HOST=$HOST BASE_PATH=$BASE_PATH WORKSPACE_ROOT=$WORKSPACE_ROOT ALLOWED_ROOT=$ALLOWED_ROOT AUTH_MODE=$AUTH_MODE AUTH_PASSWORD=$AUTH_PASSWORD APP_URL=$APP_URL SESSION_SECRET=$SESSION_SECRET GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET GOOGLE_ALLOWED_EMAILS=$GOOGLE_ALLOWED_EMAILS node dist/index.js
