export const SUPPORTED_LOCALES = ['vi', 'en'] as const;
export type Locale = typeof SUPPORTED_LOCALES[number];

type MessageTree = Record<string, any>;

export const localeLabels: Record<Locale, { nativeName: string; shortName: string; flag: string }> = {
  vi: { nativeName: 'Tiếng Việt', shortName: 'VI', flag: '🇻🇳' },
  en: { nativeName: 'English', shortName: 'EN', flag: '🇺🇸' },
};

export const messages: Record<Locale, MessageTree> = {
  vi: {
    common: { retry: 'Thử lại', close: 'Đóng', save: 'Lưu', create: 'Tạo mới', refresh: 'Tải lại', edit: 'Chỉnh sửa', delete: 'Xóa', active: 'Đang chọn', language: 'Ngôn ngữ' },
    nav: { files: 'Tệp', terminal: 'Lệnh', claude: 'Trợ lý', editor: 'Soạn thảo' },
    header: { manageServer: 'Quản lý Server & SSH', rootFolder: 'Về thư mục gốc', parentFolder: 'Thư mục cấp trên', terminalSessions: 'Danh sách cửa sổ terminal', claudeSessions: 'Danh sách phiên Claude', newWindow: 'Tạo cửa sổ mới', newClaudeSession: 'Tạo phiên Claude mới', preview: 'Xem Preview', editCode: 'Chỉnh sửa Code', saveFile: 'Lưu (Ctrl+S)', closeFile: 'Đóng file', enableCompactTask: 'Bật chế độ chỉ hiện task hiện tại', disableCompactTask: 'Tắt chế độ chỉ hiện task hiện tại', limits: 'Xem hạn mức 5h & Tuần', dirty: 'Sửa' },
    auth: { subtitle: 'Truy cập IDE mobile riêng tư', passwordLabel: 'Mật khẩu', passwordPlaceholder: 'Nhập mật khẩu', unlock: 'Mở khóa', unlocking: 'Đang mở khóa...', google: 'Tiếp tục với Google', googleHint: 'Chỉ email được cho phép mới có thể truy cập ứng dụng này.', passwordHint: 'Nhập mật khẩu ứng dụng đã cấu hình để tiếp tục.', cannotReach: 'Không thể kết nối máy chủ xác thực.', wrongPassword: 'Sai mật khẩu. Còn {count} lần thử.', locked: 'Sai quá nhiều lần. Thử lại sau {time}.', googleDenied: 'Email Google này không được phép truy cập.', loginFailed: 'Đăng nhập thất bại: {error}' },
    terminalHub: { title: 'Cửa sổ Terminal ({server})', new: 'Tạo cửa sổ Terminal mới', edit: 'Chỉnh sửa', closeDelete: 'Đóng / Xóa cửa sổ' },
    claudeHub: { title: 'Quản lý Phiên Claude', new: 'Tạo phiên mới', empty: 'Chưa có phiên Claude nào. Nhấn "+ Tạo mới" để bắt đầu.', edit: 'Chỉnh sửa đầy đủ', delete: 'Xóa', messages: 'tin nhắn', context: 'Ngữ cảnh' },
    claudeModal: { createTitle: 'Khởi chạy Phiên Claude Mới', editTitle: 'Chỉnh sửa Phiên Claude', workingDir: 'Thư mục làm việc (Working Directory)', defaultFolder: 'Về thư mục mặc định', pickFolder: 'Chọn thư mục dạng cây', sessionName: 'Tên phiên Claude', autoNamePlaceholder: 'Gợi ý tự động theo thư mục', bypassHint: 'Cho phép Claude chạy công cụ mà không yêu cầu xác nhận trong phiên này.', initialPrompt: 'Yêu cầu ban đầu (Prompt khởi động - Tùy chọn)', promptPlaceholder: 'Ví dụ: Đọc file package.json và tóm tắt cấu trúc dự án...', cancel: 'Hủy', saveChanges: 'Lưu thay đổi', launch: 'Khởi chạy Claude' },
    limits: { remaining: 'Còn {percent}% hạn mức', contextWindow: 'Phiên hiện tại (Context Window)' },
    serverModal: { title: 'Quản lý Server & SSH', sync: 'Đồng bộ', add: 'Thêm Server', addConfig: 'Thêm Cấu Hình Server Mới', hostName: 'Tên Server (Host)', hostAddress: 'Địa chỉ Host / IP', user: 'Tài khoản (User)', port: 'Cổng SSH (Port)', authMethod: 'Phương thức xác thực', availableKeys: 'Key có sẵn:', disconnect: 'Ngắt kết nối SSH', saved: 'Đã lưu', home: 'Về Home (~)', browseTree: 'Duyệt cây thư mục', cancel: 'Hủy', password: 'Mật khẩu', sshPassword: 'Mật khẩu SSH', sshPasswordPlaceholder: 'Nhập mật khẩu SSH', workspace: 'Thư mục khởi chạy', saveAdd: 'Lưu vào ~/.ssh/config & Thêm', selected: 'Đang chọn', connected: 'Kết nối nền', disconnected: 'Chưa kết nối', editWorkspace: 'Chỉnh thư mục khởi chạy' },
    terminal: { reconnecting: 'Đang tự động kết nối lại WebSocket...', expandKeys: 'Mở rộng bảng phím tắt', fontUp: 'Phóng to chữ', paste: 'Dán (Bracketed Paste)', ctrlCancel: 'Ctrl C Hủy', ctrlA: 'Ctrl A Đầu dòng', ctrlE: 'Ctrl E Cuối dòng', ctrlW: 'Ctrl W Xóa từ', ctrlU: 'Ctrl U Xóa dòng', ctrlR: 'Ctrl R Tìm lệnh', ctrlK: 'Ctrl K Xóa đến cuối', ctrlY: 'Ctrl Y Dán (yank)', altPrev: 'Alt+◄ Từ trước', altNext: 'Alt+► Từ sau', altDelete: 'Alt+D Xóa từ sau', navigation: 'Điều Hướng Trang', gitQuick: 'Git Nhanh', quickCommands: 'Lệnh Nhanh 1 Chạm', stop: 'Stop', clear: 'Clear', previousWord: 'Từ trước', nextWord: 'Từ sau', deleteNextWord: 'Xóa từ sau', pasteTitle: 'Dán Nội Dung Vào Terminal', pastePlaceholder: 'Nhập hoặc dán nội dung vào đây...', pasteNow: 'Dán Ngay' },
    terminalModal: { createTitle: 'Tạo Cửa Sổ Terminal Mới', editTitle: 'Chỉnh sửa Cửa Sổ Terminal', targetDir: 'Thư mục khởi chạy (Target Directory)', cancel: 'Hủy', saveChanges: 'Lưu thay đổi', createWindow: 'Tạo Cửa Sổ' },
    fileExplorer: { loading: 'Đang tải danh sách...', empty: 'Thư mục trống', folder: 'Thư mục', renameDescription: 'Đổi tên cho: {name}', renamePlaceholder: 'Nhập tên mới', saveChanges: 'Lưu Thay Đổi', deleteTitle: 'Xác Nhận Xóa', deleteMessage: 'Bạn có chắc chắn muốn xóa {type} "{name}"?\nHành động này không thể hoàn tác.', deleteNow: 'Xóa Ngay', file: 'tệp tin' },
    createItem: { folderTitle: 'Tạo Thư Mục Mới', fileTitle: 'Tạo Tệp Tin Mới', folder: 'Thư mục', cancel: 'Hủy', create: 'Tạo Mới' },
    folderTree: { navigating: 'Đang mở đến thư mục đã chọn...', cancel: 'Hủy', loading: 'Đang tải...' },
    inputModal: { cancel: 'Hủy', defaultTitle: 'Nhập thông tin' },
    claudeView: { thinkingFallback: 'Đang phân tích yêu cầu và codebase...', placeholder: 'Nhập yêu cầu cho Claude...', pasteTitle: 'Dán từ clipboard', stripRun: 'Chạy lệnh', stripRead: 'Đọc file', stripEdit: 'Chỉnh sửa' },
    confirm: { deleteClaudeTitle: 'Đóng Phiên Claude', deleteClaudeMessage: "Bạn có chắc chắn muốn đóng phiên chat '{name}' không?", deleteClaudeConfirm: 'Đóng Phiên' },
  },
  en: {
    common: { retry: 'Retry', close: 'Close', save: 'Save', create: 'Create', refresh: 'Refresh', edit: 'Edit', delete: 'Delete', active: 'Selected', language: 'Language' },
    nav: { files: 'Files', terminal: 'Terminal', claude: 'Claude', editor: 'Editor' },
    header: { manageServer: 'Manage Servers & SSH', rootFolder: 'Go to root folder', parentFolder: 'Parent folder', terminalSessions: 'Terminal windows', claudeSessions: 'Claude sessions', newWindow: 'New window', newClaudeSession: 'New Claude session', preview: 'Preview', editCode: 'Edit code', saveFile: 'Save (Ctrl+S)', closeFile: 'Close file', enableCompactTask: 'Show only current task', disableCompactTask: 'Disable current-task-only mode', limits: 'View 5h & weekly limits', dirty: 'Edited' },
    auth: { subtitle: 'Private mobile IDE access', passwordLabel: 'Password', passwordPlaceholder: 'Enter password', unlock: 'Unlock', unlocking: 'Unlocking...', google: 'Continue with Google', googleHint: 'Only allowed emails can access this app.', passwordHint: 'Enter the configured app password to continue.', cannotReach: 'Cannot reach auth server.', wrongPassword: 'Wrong password. {count} attempt(s) left.', locked: 'Too many failed attempts. Try again in {time}.', googleDenied: 'This Google email is not allowed.', loginFailed: 'Login failed: {error}' },
    terminalHub: { title: 'Terminal Windows ({server})', new: 'Create Terminal Window', edit: 'Edit', closeDelete: 'Close / Delete window' },
    claudeHub: { title: 'Claude Session Manager', new: 'New session', empty: 'No Claude sessions yet. Tap "+ New" to start.', edit: 'Edit session', delete: 'Delete', messages: 'messages', context: 'Context' },
    claudeModal: { createTitle: 'Start New Claude Session', editTitle: 'Edit Claude Session', workingDir: 'Working Directory', defaultFolder: 'Go to default folder', pickFolder: 'Pick folder from tree', sessionName: 'Claude session name', autoNamePlaceholder: 'Auto-suggested from folder', bypassHint: 'Allow Claude to run tools without asking for confirmation in this session.', initialPrompt: 'Initial prompt (optional)', promptPlaceholder: 'Example: Read package.json and summarize the project structure...', cancel: 'Cancel', saveChanges: 'Save changes', launch: 'Launch Claude' },
    limits: { remaining: '{percent}% quota remaining', contextWindow: 'Current Session (Context Window)' },
    serverModal: { title: 'Server & SSH Manager', sync: 'Sync', add: 'Add Server', addConfig: 'Add New Server Config', hostName: 'Server Name (Host)', hostAddress: 'Host / IP Address', user: 'Account (User)', port: 'SSH Port', authMethod: 'Authentication method', availableKeys: 'Available keys:', disconnect: 'Disconnect SSH', saved: 'Saved', home: 'Go Home (~)', browseTree: 'Browse folder tree', cancel: 'Cancel', password: 'Password', sshPassword: 'SSH Password', sshPasswordPlaceholder: 'Enter SSH password', workspace: 'Startup directory', saveAdd: 'Save to ~/.ssh/config & Add', selected: 'Selected', connected: 'Background connection', disconnected: 'Not connected', editWorkspace: 'Edit startup directory' },
    terminal: { reconnecting: 'Automatically reconnecting WebSocket...', expandKeys: 'Expand shortcut keys', fontUp: 'Increase font size', paste: 'Paste (Bracketed Paste)', ctrlCancel: 'Ctrl C Cancel', ctrlA: 'Ctrl A Line start', ctrlE: 'Ctrl E Line end', ctrlW: 'Ctrl W Delete word', ctrlU: 'Ctrl U Delete line', ctrlR: 'Ctrl R Search history', ctrlK: 'Ctrl K Delete to end', ctrlY: 'Ctrl Y Paste (yank)', altPrev: 'Alt+◄ Previous word', altNext: 'Alt+► Next word', altDelete: 'Alt+D Delete next word', navigation: 'Page Navigation', gitQuick: 'Quick Git', quickCommands: 'One-Tap Commands', stop: 'Stop', clear: 'Clear', previousWord: 'Previous word', nextWord: 'Next word', deleteNextWord: 'Delete next word', pasteTitle: 'Paste Content Into Terminal', pastePlaceholder: 'Type or paste content here...', pasteNow: 'Paste Now' },
    terminalModal: { createTitle: 'Create New Terminal Window', editTitle: 'Edit Terminal Window', targetDir: 'Startup directory (Target Directory)', cancel: 'Cancel', saveChanges: 'Save changes', createWindow: 'Create Window' },
    fileExplorer: { loading: 'Loading file list...', empty: 'Empty folder', folder: 'Folder', renameDescription: 'Rename: {name}', renamePlaceholder: 'Enter new name', saveChanges: 'Save Changes', deleteTitle: 'Confirm Delete', deleteMessage: 'Are you sure you want to delete this {type} "{name}"?\nThis action cannot be undone.', deleteNow: 'Delete Now', file: 'file' },
    createItem: { folderTitle: 'Create New Folder', fileTitle: 'Create New File', folder: 'Folder', cancel: 'Cancel', create: 'Create' },
    folderTree: { navigating: 'Opening selected folder...', cancel: 'Cancel', loading: 'Loading...' },
    inputModal: { cancel: 'Cancel', defaultTitle: 'Enter information' },
    claudeView: { thinkingFallback: 'Analyzing request and codebase...', placeholder: 'Ask Claude...', pasteTitle: 'Paste from clipboard', stripRun: 'Run command', stripRead: 'Read file', stripEdit: 'Edit' },
    confirm: { deleteClaudeTitle: 'Close Claude Session', deleteClaudeMessage: "Are you sure you want to close chat session '{name}'?", deleteClaudeConfirm: 'Close Session' },
  },
};
